#!/bin/sh

pgrep -x dmenu && exit

getmount() { \
  [ -z "$chosen" ] && exit 1
  mp="$(find $1 | dmenu -fn Hack -nb '#000000' -i -p "Type in mount point.")"
  [ "$mp" = "" ] && exit 1
  if [ ! -d "$mp" ]; then
    mkdiryn=$(printf "No\\nYes" | dmenu -fn Hack -nb '#000000' -i -p "$mp does not exist. Create it?")
    [ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
  fi
}

mountusb() { \
  chosen="$(echo "$usbdrives" | dmenu -fn Hack -nb '#000000' -i -p "Mount which drive?" | awk '{print $1}')"
  sudo -A mount "$chosen" && notify-send "$chosen mounted." && exit 0
  if [ $a -eq 1 ]; then
    exit 1
  fi
  getmount "/mnt /media /mount /home -maxdepth 5 -type d"
  partitiontype="$(lsblk -no "fstype" "$chosen")"
  case "$partitiontype" in
    "vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
    *) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" 741 "$mp";;
  esac
  notify-send "$chosen mounted to $mp."
}

unmountusb() {
	sudo -A umount "$mp" && pgrep -x dunst && notify-send "$mp unmounted."
	}

borgbackup() { \
  mountusb
  passwd="$(dmenu -fn Hack -nb '#000000' -sb "#d79921" -sf "#1d2021" -nf "#000000" -p "Type in backup passphrase" <&-)"
  export BORG_PASSPHRASE=$passwd
  sudo -A -E "path to autobackup.sh"/autobackup.sh "$mp" > /tmp/borg_log 2>&1
  if [ $? -eq 2 ]; then
    notify-send "Wrong password"
    rm -f /tmp/borg_log
    unmountusb
    exit 1
  fi
  notify-send -u critical "Backup successfull"
  rm -f /tmp/borg_log
  unmountusb
}

usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbdrives" ]; then
  echo "No USB drive or Android device detected" && exit
else
  borgbackup
fi
